name: Web CloudFront deploy
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: 'Test'
        required: false
        type: string
      domain:
        description: 'The domain to deploy to'
        default: 'test.web.dap.aero'
        required: false
        type: string
      cloudfront-distribution-id:
        description: 'The ID of the cloudfront distribution'
        required: true
        type: string
      bucket-prefix:
        description: 'The prefix for upload buckets'
        required: true
        type: string
      node-version:
        description: 'Version of node to deploy with'
        default: '20.x'
        required: false
        type: string
      artifact-name:
        description: 'Artifact to deploy'
        default: build-20.x
        required: false
        type: string
    secrets:
      amazon_role:
        description: The AWS role to assume
        required: true
      npm_pat:
        description: The PAT for NPM registry access
        required: true

jobs:
  deploy_cloudfront:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: "Deploy to ${{ inputs.environment }} CloudFront"
    env:
      ENVIRONMENT_NAME: ${{ inputs.environment }}
    steps:
      - name: Lowercase enviromnent name
        run: |
          echo "ENVIRONMENT=${ENVIRONMENT_NAME,,}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --production=false --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          merge-multiple: true
          name: ${{ inputs.artifact-name }}
          path: out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.amazon_role }}

      - name: Deploy website
        env:
          DEPLOY_DISTRIBUTION_ID: "${{ inputs.cloudfront-distribution-id }}"
          DEPLOY_BUCKET_PREFIX: "${{ inputs.bucket-prefix }}"
          SITE_ROOT: "https://${{ inputs.domain }}"
        run: yarn deploy
