name: Axe accessibility check
on:
  workflow_call:
    secrets:
      npm_pat:
        description: The PAT for NPM registry access
        required: true

jobs:
  axe:
    runs-on: ubuntu-latest
    name: "Axe accessibility check"
    strategy:
      matrix:
        node-version: ["20.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Install dependencies
        run: yarn install --production=false --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PAT}}

      - name: Get Chromium version
        run: |
          # Broken with 124: https://github.com/giggio/node-chromedriver/issues/467
          # CHROMIUM_VERSION=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE | cut -d. -f1)
          CHROMIUM_VERSION=123
          echo "Chromium version: $CHROMIUM_VERSION"
          echo "CHROMIUM_VERSION=$CHROMIUM_VERSION" >> "$GITHUB_ENV"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416 # v2.1.0
        with:
          chrome-version: ${{ env.CHROMIUM_VERSION }}

      - name: Install chromedriver
        run: yarn add chromedriver@"$CHROMIUM_VERSION"

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          merge-multiple: true
          name: build-${{ matrix.node-version }}
          path: out

      - name: Install axe
        run: yarn global add @axe-core/cli

      - name: Run axe accessibility test
        run: axe --stdout --chromedriver-path "$(yarn bin)/chromedriver/bin/chromedriver" "file://$(pwd)/out/index.html" --exit
